# Sample container configuration

[[containers]]
repository = "docker.io"
name = "library/busybox"
tag = "latest"
architectures = ["linux/amd64", "linux/arm64", "linux/arm/v7"]

[[containers]]
repository = "docker.io"
name = "library/postgres"
tag = "16-alpine"
architectures = ["linux/amd64", "linux/arm64"]

[[containers]]
repository = "ghcr.io"
name = "home-assistant/home-assistant"
tag = "latest"
architectures = ["linux/amd64"]

[[containers]]
repository = "docker.gitea.com"
name = "gitea"
tag = "latest"
architectures = ["linux/amd64"]
