# Sample container configuration

[repositories]
docker = "https://registry-1.docker.io"
github = "https://ghcr.io"

[[containers]]
repository = "docker"
name = "library/busybox"
tag = "latest"
architectures = ["linux/amd64", "linux/arm64", "linux/arm/v7"]

[[containers]]
repository = "docker"
name = "library/alpine"
tag = "3.14"
architectures = ["linux/amd64", "linux/arm64"]

[[containers]]
repository = "github"
name = "fred-drake/python-ssh"
tag = "latest"
architectures = ["linux/amd64"]
